# render PDF
renderthis::to_pdf("materials/0_getStarted/0_getStarted.html")
renderthis::to_pdf("materials/1_intro/1.1_intro.html")
renderthis::to_pdf("materials/1_intro/1.2_intro.html")
renderthis::to_pdf("materials/1_intro/1.3_funzioni&errori.html")
renderthis::to_pdf("materials/2_struttureDati/2.1_vettori.html")
renderthis::to_pdf("materials/2_struttureDati/2.2_fattori.html")
renderthis::to_pdf("materials/2_struttureDati/2.3_liste&matrici&array.html")
renderthis::to_pdf("materials/2_struttureDati/2.4_dataframe.html")
renderthis::to_pdf("materials/3_programmazione/3.1_condizionale.html")
renderthis::to_pdf("materials/3_programmazione/3.2_iterativa.html")
renderthis::to_pdf("materials/3_programmazione/3.3_apply.html")
